<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('products')->insert([
            ['name'=>'Latsas', 'product_type_id'=>1, 'stock'=>450, 'price'=>179900,
            'description'=>'12-piece shopping cart / shopping basket set', 'image'=> '/storage/images/ChildrenToys011.jpg'],
            ['name'=>'Duktig', 'product_type_id'=>1, 'stock'=>300, 'price'=>149000,
            'description'=>'14-piece vegetables basket set', 'image'=> '/storage/images/ChildrenToys012.jpg'],
            ['name'=>'Lustigt', 'product_type_id'=>1, 'stock'=>350, 'price'=>299000,
            'description'=>'Dart game with octopus', 'image'=> '/storage/images/ChildrenToys013.jpg'],
            ['name'=>'Jattelik', 'product_type_id'=>1, 'stock'=>331, 'price'=>149000,
            'description'=>'Soft toy, dinosaur / triceratops', 'image'=> '/storage/images/ChildrenToys001.jpg'],
            ['name'=>'Jattelik', 'product_type_id'=>1, 'stock'=>350, 'price'=>149000,
            'description'=>'Soft toy, dinosaur / stegosaurus', 'image'=> '/storage/images/ChildrenToys002.jpg'],
            ['name'=>'Jattelik', 'product_type_id'=>1, 'stock'=>300, 'price'=>149000,
            'description'=>'Soft toy, dinosaur / velociraptor', 'image'=> '/storage/images/ChildrenToys006.jpg'],
            ['name'=>'Jattelik', 'product_type_id'=>1, 'stock'=>300, 'price'=>149000,
            'description'=>'Soft toy, dinosaur / brontosaurus', 'image'=> '/storage/images/ChildrenToys007.jpg'],
            ['name'=>'Jattelik', 'product_type_id'=>1, 'stock'=>120, 'price'=>349000,
            'description'=>'12-piece dinosaur world set', 'image'=> '/storage/images/ChildrenToys015.jpg'],
            ['name'=>'Lilleplutt', 'product_type_id'=>1, 'stock'=>300, 'price'=>89000,
            'description'=>'Soft toy, cat grey white, 40 cm', 'image'=> '/storage/images/ChildrenToys003.jpg'],
            ['name'=>'Vandring Hare', 'product_type_id'=>1, 'stock'=>250, 'price'=>99900,
            'description'=>'Soft toy, hare bunny grey', 'image'=> '/storage/images/ChildrenToys004.jpg'],
            ['name'=>'Hoppig', 'product_type_id'=>1, 'stock'=>250, 'price'=>99900,
            'description'=>'Soft toy, dog / mountain dog', 'image'=> '/storage/images/ChildrenToys005.jpg'],
            ['name'=>'Knorrig', 'product_type_id'=>1, 'stock'=>289, 'price'=>149000,
            'description'=>'Soft toy, pig pink, 40 cm', 'image'=> '/storage/images/ChildrenToys008.jpg'],
            ['name'=>'Livlig', 'product_type_id'=>1, 'stock'=>1009, 'price'=>279000,
            'description'=>'Soft toy, dog / husky, 80 cm', 'image'=> '/storage/images/ChildrenToys009.jpg'],
            ['name'=>'Kramig', 'product_type_id'=>1, 'stock'=>500, 'price'=>79900,
            'description'=>'Soft toy, panda, 50 cm', 'image'=> '/storage/images/ChildrenToys010.jpg'],
            ['name'=>'Blahaj', 'product_type_id'=>1, 'stock'=>350, 'price'=>249000,
            'description'=>'Soft toy, shark blue', 'image'=> '/storage/images/ChildrenToys014.jpg'],
            ['name'=>'Djungelskog', 'product_type_id'=>1, 'stock'=>120, 'price'=>329000,
            'description'=>'Soft toy, brown bear', 'image'=> '/storage/images/ChildrenToys016.jpg'],

            ['name'=>'Vinter 2020', 'product_type_id'=>2, 'stock'=>300, 'price'=>59900,
            'description'=>'Top star, gold color', 'image'=> '/storage/images/Christmas001.jpg'],
            ['name'=>'Vinter 2020', 'product_type_id'=>2, 'stock'=>299, 'price'=>59900,
            'description'=>'Hanging decoration, snowflake', 'image'=> '/storage/images/Christmas002.jpg'],
            ['name'=>'Vinter 2020', 'product_type_id'=>2, 'stock'=>250, 'price'=>299900,
            'description'=>'Decoration wreath, red color', 'image'=> '/storage/images/Christmas003.jpg'],
            ['name'=>'Vinter 2020', 'product_type_id'=>2, 'stock'=>250, 'price'=>129000,
            'description'=>'Decoration baubel, animal pattern', 'image'=> '/storage/images/Christmas004.jpg'],
            ['name'=>'Vinter 2020', 'product_type_id'=>2, 'stock'=>220, 'price'=>129000,
            'description'=>'Decoration set of 2, Santa Claus', 'image'=> '/storage/images/Christmas005.jpg'],
            ['name'=>'Vinter 2020', 'product_type_id'=>2, 'stock'=>399, 'price'=>129000,
            'description'=>'Decoration, mini christmas tree, green', 'image'=> '/storage/images/Christmas006.jpg'],

            ['name'=>'Micke', 'product_type_id'=>3, 'stock'=>1000, 'price'=>2999000,
            'description'=>'Corner workstation, black-brown', 'image'=> '/storage/images/Desk001.jpg'],
            ['name'=>'Micke', 'product_type_id'=>3, 'stock'=>779, 'price'=>1499000,
            'description'=>'Desk, white color', 'image'=> '/storage/images/Desk003.jpg'],
            ['name'=>'Vittsjo', 'product_type_id'=>3, 'stock'=>889, 'price'=>699000,
            'description'=>'Laptop table, black-brown / glass', 'image'=> '/storage/images/Desk002.jpg'],
            ['name'=>'Micke', 'product_type_id'=>3, 'stock'=>1999, 'price'=>999000,
            'description'=>'Desk, black-brown color', 'image'=> '/storage/images/Desk007.jpg'],
            ['name'=>'Fredde', 'product_type_id'=>3, 'stock'=>1190, 'price'=>3499000,
            'description'=>'Desk, black color', 'image'=> '/storage/images/Desk004.jpg'],
            ['name'=>'Malm', 'product_type_id'=>3, 'stock'=>1009, 'price'=>2299000,
            'description'=>'Desk with pull-out panel, white', 'image'=> '/storage/images/Desk005.jpg'],
            ['name'=>'Alex', 'product_type_id'=>3, 'stock'=>1999, 'price'=>2999000,
            'description'=>'Desk with pull-out panel, white', 'image'=> '/storage/images/Desk006.jpg'],

            ['name'=>'Billy', 'product_type_id'=>4, 'stock'=>990, 'price'=>4947000,
            'description'=>'Bookcase, black-brown', 'image'=> '/storage/images/Bookshelf001.jpg'],
            ['name'=>'Billy', 'product_type_id'=>4, 'stock'=>1990, 'price'=>2997000,
            'description'=>'Bookcase, white stained oak veneer', 'image'=> '/storage/images/Bookshelf002.jpg'],
            ['name'=>'Billy', 'product_type_id'=>4, 'stock'=>2990, 'price'=>3198000,
            'description'=>'Bookcase, white stained oak veneer', 'image'=> '/storage/images/Bookshelf003.jpg'],
            ['name'=>'Billy', 'product_type_id'=>4, 'stock'=>2990, 'price'=>1649000,
            'description'=>'Bookcase, black-brown', 'image'=> '/storage/images/Bookshelf004.jpg'],
            ['name'=>'Hemnes', 'product_type_id'=>4, 'stock'=>100, 'price'=>8497000,
            'description'=>'Bookcase, white stain', 'image'=> '/storage/images/Bookshelf005.jpg'],
            ['name'=>'Billy', 'product_type_id'=>4, 'stock'=>690, 'price'=>8300000,
            'description'=>'Bookcase, combination stained oak', 'image'=> '/storage/images/Bookshelf006.jpg'],
            ['name'=>'Billy/Oxberg', 'product_type_id'=>4, 'stock'=>199, 'price'=>3948000,
            'description'=>'Bookcase, with panel / glass doors', 'image'=> '/storage/images/Bookshelf007.jpg'],
            ['name'=>'Laiva', 'product_type_id'=>4, 'stock'=>299, 'price'=>399000,
            'description'=>'Bookcase, black-brown color', 'image'=> '/storage/images/Bookshelf008.jpg'],
            ['name'=>'Lommarp', 'product_type_id'=>4, 'stock'=>1005, 'price'=>2799000,
            'description'=>'Bookcase, dark blue-green', 'image'=> '/storage/images/Bookshelf009.jpg'],
            ['name'=>'Liatorp', 'product_type_id'=>4, 'stock'=>302, 'price'=>4999000,
            'description'=>'Bookcase, white', 'image'=> '/storage/images/Bookshelf010.jpg'],
            ['name'=>'Hemnes', 'product_type_id'=>4, 'stock'=>402, 'price'=>8497000,
            'description'=>'Bookcase, light brown', 'image'=> '/storage/images/Bookshelf011.jpg'],
            ['name'=>'Billy/Oxberg', 'product_type_id'=>4, 'stock'=>402, 'price'=>8497000,
            'description'=>'Bookcase with door, black-brown', 'image'=> '/storage/images/Bookshelf012.jpg'],

            ['name'=>'Nordli', 'product_type_id'=>5, 'stock'=>609, 'price'=>7499000,
            'description'=>'Bed frame with storage, white', 'image'=> '/storage/images/Bed011.jpg'],
            ['name'=>'Hemnes', 'product_type_id'=>5, 'stock'=>1120, 'price'=>5199000,
            'description'=>'Bed frame, black-brown', 'image'=> '/storage/images/Bed001.jpg'],
            ['name'=>'Tarva', 'product_type_id'=>5, 'stock'=>1000, 'price'=>2699000,
            'description'=>'Bed frame, pine', 'image'=> '/storage/images/Bed002.jpg'],
            ['name'=>'Songesand', 'product_type_id'=>5, 'stock'=>999, 'price'=>4299000,
            'description'=>'Bed frame, brown', 'image'=> '/storage/images/Bed003.jpg'],
            ['name'=>'Askvoll', 'product_type_id'=>5, 'stock'=>668, 'price'=>3499000,
            'description'=>'Bed frame, white', 'image'=> '/storage/images/Bed004.jpg'],
            ['name'=>'Malm', 'product_type_id'=>5, 'stock'=>668, 'price'=>3499000,
            'description'=>'Bed frame, high, white stained oak', 'image'=> '/storage/images/Bed005.jpg'],
            ['name'=>'Malm', 'product_type_id'=>5, 'stock'=>332, 'price'=>5399000,
            'description'=>'Bed frame, high, brown stained oak', 'image'=> '/storage/images/Bed006.jpg'],
            ['name'=>'Platsa', 'product_type_id'=>5, 'stock'=>668, 'price'=>4950000,
            'description'=>'Bed frame with storage, white', 'image'=> '/storage/images/Bed007.jpg'],
            ['name'=>'Gjora', 'product_type_id'=>5, 'stock'=>298, 'price'=>5199000,
            'description'=>'Bed frame, birch', 'image'=> '/storage/images/Bed008.jpg'],
            ['name'=>'Kopardal', 'product_type_id'=>5, 'stock'=>189, 'price'=>3199000,
            'description'=>'Bed frame, grey', 'image'=> '/storage/images/Bed009.jpg'],
            ['name'=>'Sagstua', 'product_type_id'=>5, 'stock'=>609, 'price'=>3799000,
            'description'=>'Bed frame, black', 'image'=> '/storage/images/Bed010.jpg'],

            ['name'=>'Nordli', 'product_type_id'=>6, 'stock'=>700, 'price'=>4999000,
            'description'=>'Chest of 7 drawers, white', 'image'=> '/storage/images/Drawer001.jpg'],
            ['name'=>'Nordli', 'product_type_id'=>6, 'stock'=>499, 'price'=>4799000,
            'description'=>'Chest of 8 drawers, white', 'image'=> '/storage/images/Drawer002.jpg'],
            ['name'=>'Nordli', 'product_type_id'=>6, 'stock'=>330, 'price'=>7697000,
            'description'=>'Chest of 8 drawers, anthracite', 'image'=> '/storage/images/Drawer003.jpg'],
            ['name'=>'Nikkeby', 'product_type_id'=>6, 'stock'=>450, 'price'=>1499000,
            'description'=>'Chest of 4 drawers, red', 'image'=> '/storage/images/Drawer004.jpg'],
            ['name'=>'Musken', 'product_type_id'=>6, 'stock'=>1299, 'price'=>1999000,
            'description'=>'Chest of 4 drawers, white', 'image'=> '/storage/images/Drawer005.jpg'],
            ['name'=>'Hemnes', 'product_type_id'=>6, 'stock'=>699, 'price'=>6999000,
            'description'=>'Chest of 8 drawers, white stain', 'image'=> '/storage/images/Drawer006.jpg'],
            ['name'=>'Hemnes', 'product_type_id'=>6, 'stock'=>500, 'price'=>2999000,
            'description'=>'Chest of 3 drawers, black-brown', 'image'=> '/storage/images/Drawer007.jpg'],
            ['name'=>'Hemnes', 'product_type_id'=>6, 'stock'=>1299, 'price'=>1799000,
            'description'=>'Chest of 5 drawers, white stained oak', 'image'=> '/storage/images/Drawer008.jpg'],
            ['name'=>'Nordmela', 'product_type_id'=>6, 'stock'=>100, 'price'=>3999000,
            'description'=>'Chest of 4 drawers, black-blue', 'image'=> '/storage/images/Drawer009.jpg'],
            ['name'=>'Songesand', 'product_type_id'=>6, 'stock'=>1254, 'price'=>3999000,
            'description'=>'Chest of 6 drawers, brown', 'image'=> '/storage/images/Drawer010.jpg'],
            ['name'=>'Malm', 'product_type_id'=>6, 'stock'=>1000, 'price'=>1699000,
            'description'=>'Chest of 3 drawers, white stained oak', 'image'=> '/storage/images/Drawer011.jpg'],
            ['name'=>'Trysil', 'product_type_id'=>6, 'stock'=>599, 'price'=>1299000,
            'description'=>'Chest of 4 drawers, brown', 'image'=> '/storage/images/Drawer012.jpg'],
            ['name'=>'Tyssedal', 'product_type_id'=>6, 'stock'=>800, 'price'=>3999000,
            'description'=>'Chest of 4 drawers, white', 'image'=> '/storage/images/Drawer013.jpg'],
            ['name'=>'Brimnes', 'product_type_id'=>6, 'stock'=>409, 'price'=>2299000,
            'description'=>'Chest of 4 drawers, white / glass', 'image'=> '/storage/images/Drawer014.jpg'],
            ['name'=>'Askvoll', 'product_type_id'=>6, 'stock'=>800, 'price'=>1299000,
            'description'=>'Chest of 3 drawers, white', 'image'=> '/storage/images/Drawer015.jpg'],

            ['name'=>'Rakkestad', 'product_type_id'=>7, 'stock'=>100, 'price'=>2399000,
            'description'=>'Wardrobe with 3 doors, black-brown', 'image'=> '/storage/images/Wardrobe001.jpg'],
            ['name'=>'Kleppstad', 'product_type_id'=>7, 'stock'=>299, 'price'=>1399000,
            'description'=>'Wardrobe with 2 doors, white', 'image'=> '/storage/images/Wardrobe002.jpg'],
            ['name'=>'Brimnes', 'product_type_id'=>7, 'stock'=>1000, 'price'=>2599000,
            'description'=>'Wardrobe with 3 doors, white', 'image'=> '/storage/images/Wardrobe003.jpg'],
            ['name'=>'Songesand', 'product_type_id'=>7, 'stock'=>12, 'price'=>3499000,
            'description'=>'Wardrobe, brown', 'image'=> '/storage/images/Wardrobe004.jpg'],
            ['name'=>'Songesand', 'product_type_id'=>7, 'stock'=>54, 'price'=>3499000,
            'description'=>'Wardrobe, white', 'image'=> '/storage/images/Wardrobe006.jpg'],
            ['name'=>'Rakkestad', 'product_type_id'=>7, 'stock'=>992, 'price'=>2799000,
            'description'=>'Wardrobe with sliding doors, black', 'image'=> '/storage/images/Wardrobe005.jpg'],
            ['name'=>'Hemnes', 'product_type_id'=>7, 'stock'=>320, 'price'=>3499000,
            'description'=>'Open wardrobe, white', 'image'=> '/storage/images/Wardrobe007.jpg'],
            ['name'=>'Nordkisa', 'product_type_id'=>7, 'stock'=>1999, 'price'=>3299000,
            'description'=>'Open wardrobe, bamboo', 'image'=> '/storage/images/Wardrobe008.jpg'],
            ['name'=>'Kleppstad', 'product_type_id'=>7, 'stock'=>299, 'price'=>2399000,
            'description'=>'Wardrobe with sliding doors, white', 'image'=> '/storage/images/Wardrobe009.jpg'],

            ['name'=>'Skuggbracka', 'product_type_id'=>8, 'stock'=>3000, 'price'=>499000,
            'description'=>'Quilt cover and 2 pillowcases, white/black', 'image'=> '/storage/images/Bedlinens001.jpg'],
            ['name'=>'Smalstakra', 'product_type_id'=>8, 'stock'=>2997, 'price'=>899000,
            'description'=>'Quilt cover and 2 pillowcases, stripes', 'image'=> '/storage/images/Bedlinens002.jpg'],
            ['name'=>'Alandsrot', 'product_type_id'=>8, 'stock'=>199, 'price'=>699000,
            'description'=>'Quilt cover and 2 pillowcases, floral', 'image'=> '/storage/images/Bedlinens003.jpg'],
            ['name'=>'Randgras', 'product_type_id'=>8, 'stock'=>200, 'price'=>699000,
            'description'=>'Quilt cover and 2 pillowcases, stripes', 'image'=> '/storage/images/Bedlinens004.jpg'],
            ['name'=>'Kransrams', 'product_type_id'=>8, 'stock'=>7, 'price'=>699000,
            'description'=>'Quilt cover and 2 pillowcases, gold', 'image'=> '/storage/images/Bedlinens005.jpg'],

            ['name'=>'Hemlingby', 'product_type_id'=>9, 'stock'=>45, 'price'=>2995000,
            'description'=>'Two-seat sofa, Bomstad black', 'image'=> '/storage/images/sofas001.jpg'],
            ['name'=>'Klippan', 'product_type_id'=>9, 'stock'=>200, 'price'=>2895000,
            'description'=>'Two-seat sofa, Vissle grey', 'image'=> '/storage/images/sofas002.jpg'],
            ['name'=>'Knopparp', 'product_type_id'=>9, 'stock'=>185, 'price'=>1995000,
            'description'=>'Two-seat sofa, Knisa light grey', 'image'=> '/storage/images/sofas003.jpg'],
            ['name'=>'Soderhamn', 'product_type_id'=>9, 'stock'=>3200, 'price'=>9995000,
            'description'=>'3-seat sofa, Samsta orange', 'image'=> '/storage/images/sofas004.jpg'],
            ['name'=>'Ektorp', 'product_type_id'=>9, 'stock'=>3200, 'price'=>5995000,
            'description'=>'3-seat sofa, Hallarp beige', 'image'=> '/storage/images/sofas005.jpg'],
            ['name'=>'Klippan', 'product_type_id'=>9, 'stock'=>3200, 'price'=>4999000,
            'description'=>'2 seat sofa, Storvreta red/white', 'image'=> '/storage/images/sofas006.jpg'],
            ['name'=>'Farlov', 'product_type_id'=>9, 'stock'=>3200, 'price'=>3000000,
            'description'=>'3 seat sofa, flodafors grey', 'image'=> '/storage/images/sofas007.jpg'],
        ]);
    }
}
